# Nextest configuration for cmdai
# See https://nexte.st/book/configuration.html for more options

[profile.default]
# Don't cancel the test run on the first failure.
fail-fast = false

# Run at most 4 tests concurrently.
test-threads = 4

# Set the max time a test can run before timing out.
slow-timeout = { period = "30s", terminate-after = 3 }

# Hide output for passing tests.
success-output = "never"

# Always show stderr for failing tests.
failure-output = "immediate-final"

# Show output for tests as they're running.
status-level = "pass"

[profile.default.junit]
# Store JUnit report at this path.
path = "target/nextest/junit.xml"

[profile.ci]
# CI profile - more verbose output for debugging
fail-fast = false
test-threads = 2
slow-timeout = { period = "60s", terminate-after = 5 }
success-output = "never"
failure-output = "immediate-final"
status-level = "fail"

[profile.ci.junit]
path = "target/nextest/ci-junit.xml"

[profile.verbose]
# Verbose profile for detailed debugging
fail-fast = false
test-threads = 1
slow-timeout = { period = "120s", terminate-after = 5 }
success-output = "immediate-final"
failure-output = "immediate-final"
status-level = "all"

# Override for specific test patterns
[[profile.default.overrides]]
# Async tests might need more time
filter = 'test(backend) | test(integration)'
slow-timeout = { period = "60s", terminate-after = 3 }

[[profile.default.overrides]]
# Property tests can be slow
filter = 'test(property)'
slow-timeout = { period = "120s", terminate-after = 5 }

[[profile.default.overrides]]
# Performance benchmarks need special handling
filter = 'test(performance) | test(bench)'
slow-timeout = { period = "300s", terminate-after = 5 }

# Environment variables for all test runs
[env]
RUST_LOG = "warn"
RUST_BACKTRACE = "1"

# Test environment for tokio tests
[env.tokio]
TOKIO_WORKER_THREADS = "2"

# Custom test groups
[test-groups]
async-tests = { max-threads = 2 }
property-tests = { max-threads = 1 }